//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angelfish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Angelfish.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	0.2	0.05	0.0367	0.0649
        ///1	0.2	0.1	0.055	0.062
        ///2	0.2	0.1	0.01	0.047
        ///3	0.2	0.1	0.014	0.053
        ///4	0.2	0.1	0.026	0.051
        ///5	0.2	0.1	0.014	0.039
        ///6	0.2	0.1	0.022	0.051
        ///7	0.2	0.2	0.1	0.026	0.055
        ///8	0.2	0.2	0.1	0.042	0.059
        ///9	0.2	0.2	0.1	0.03	0.055
        ///10	0.2	0.2	0.1	0.022	0.059
        ///11	0.2	0.1	0.018	0.055
        ///12	0.2	0.1	0.026	0.059
        ///13	0.2	0.1	0.034	0.063
        ///14	0.2	0.1	0.062	0.061
        ///15	0.2	0.1	0.046	0.0594
        ///16	0.2	0.1	0.03	0.057
        ///17	0.2	0.1	0.038	0.061
        ///18	0.2	0.1	0.046	0.065
        ///19	0.2	0.1	0.058	0.065
        ///20	0.2	0.1	0.014	0.047
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputs2D {
            get {
                return ResourceManager.GetString("inputs2D", resourceCulture);
            }
        }
    }
}
