//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angelfish.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Angelfish.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dA,dB,f,k,solid %,parts,type,mass
        ///0.2,0.05,0.0367,0.0649,&quot;0,27&quot;,1092,mu/theta,10650
        ///0.2,0.1,0.055,0.062,&quot;0,32&quot;,19,gamma,12784
        ///0.3,0.1,0.055,0.062,&quot;0,46&quot;,7,theta,18384
        ///0.3,0.05,0.0367,0.0649,&quot;0,30&quot;,1176,mu/theta,11879
        ///0.3,0.1,0.0367,0.0649,&quot;0,25&quot;,1030,eta,10063
        ///0.35,0.2,0.055,0.062,&quot;0,22&quot;,61,kappa,8962
        ///0.4,0.1,0.055,0.062,&quot;0,44&quot;,55,theta,17622
        ///0.4,0.2,0.055,0.062,&quot;0,30&quot;,4,kappa,11878
        ///0.4,0.05,0.0367,0.0649,&quot;0,35&quot;,674,mu/theta,13991
        ///0.4,0.1,0.0367,0.0649,&quot;0,26&quot;,1141,eta,10474
        ///0.4,0.2,0.0367,0.0649, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputs2D {
            get {
                return ResourceManager.GetString("inputs2D", resourceCulture);
            }
        }
    }
}
